const os = require("os");
console.log(os.arch());
const totalMamory = os.totalmem();
console.log(`${totalMamory/1024/1024/1024}`);
const freeMamory = os.freemem();
console.log(`${freeMamory/1024/1024/1024}`);
console.log(os.hostname());
console.log(os.platform());
console.log(os.type());
console.log(os.tmpdir());